#!/bin/sh

# Default values
# /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate : 10000
# /sys/devices/system/cpu/cpufreq/ondemand/up_threshold : 95
# /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy : 0
# /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor : 1
# /sys/devices/system/cpu/cpufreq/ondemand/down_differential : 3
# /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core : 80
# /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core : does not exist
# /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq : 300000
# /sys/devices/system/cpu/cpufreq/ondemand/sync_freq : 300000
# /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load : 80
# /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq : 300000

echo 50000 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo 90 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
echo 2 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo 10 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
echo 70 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
# echo 3 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
echo 300000 > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
echo 300000 > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load
echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 787200 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
